### PR TITLE
use xtarfile instead of tarfile for zstd support

### PR DESCRIPTION
**Pull request by coderobe**

### CODE REVIEW

**Comment by jelly** [comment]
@svenstaro this does not work at all right?

**Comment by svenstaro** [comment]
There is more to be done than this, yes. We gotta fix that xtarfile lib.

**Comment by coderobe** [comment]
Yes, we figured out that xtarfile is kinda weird. Need a different solution. Honestly should just rewrite this python script in rust, as rusts (x)tarfile works fine in this scenario.

**Comment by jelly** [comment]
Rewriting it in rust is not an acceptable solution, the current Python code is well tested and heavily relies on the internetarchive Python library.

**Comment by coderobe** [comment]
Ah, yeah, good point

**Pull request closed without merging**
